---
version: '3.8'

services:
  model-training:
    build: .
    volumes:
      - .:/app
      - ./runs:/app/runs  # Mount TensorBoard logs
    environment:
      - PYTHONPATH=/app
    command: python src/model.py

  model-testing:
    build: .
    volumes:
      - .:/app
    environment:
      - PYTHONPATH=/app
    command: pytest tests/ -v

  jupyter:
    build: .
    ports:
      - "8888:8888"
    volumes:
      - .:/app
    environment:
      - PYTHONPATH=/app
    command: jupyter notebook --ip=0.0.0.0 --port=8888 --no-browser --allow-root
